### ISSUE TITLE
example handshaker.py not working in python 3.7.3

### ISSUE THREAD

**Issue by moraorviz** [mediawiki-utilities/python-mwoauth#30]
I was doing the example in handshaker.py against a dockerized wikibase instance and it fails to parse my query string.

```Sending requests with default User-Agent.  Set 'user_agent' on mwoauth.flask.MWOAuth to quiet this message.
Point your browser to: http://xx.xxx.xx.xx:8181/w/index.php?title=Special%3AOAuth%2Fauthenticate&oauth_token=4437d38d1cd7e9438b8d03addd1f72e9&oauth_consumer_key=9945b72c40e6f5a3305f82682912d875
Response query string: oauth_verifier=bf0ce9000a5922a448e62e0adc2327e8&oauth_token=4437d38d1cd7e9438b8d03addd1f72e9
AccessToken(key=b'e1e2f94a426296e7734deec4771c3578', secret=b'7f6c4fc8caafa5183144b1d5b4bb532c7d6d7ef7')
Traceback (most recent call last):
  File "/home/mario/MyProjects/Python/wikibot/venv/lib/python3.7/site-packages/jwt/api_jws.py", line 191, in _load
    header = json.loads(header_data.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mario/MyProjects/Python/wikibot/venv/lib/python3.7/site-packages/mwoauth/functions.py", line 264, in identify
    leeway=leeway)
  File "/home/mario/MyProjects/Python/wikibot/venv/lib/python3.7/site-packages/jwt/api_jwt.py", line 84,
in decode
    payload, _, _, _ = self._load(jwt)
  File "/home/mario/MyProjects/Python/wikibot/venv/lib/python3.7/site-packages/jwt/api_jws.py", line 193, in _load
    raise DecodeError('Invalid header string: %s' % e)
jwt.exceptions.DecodeError: Invalid header string: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 29, in <module>
    main()
  File "bot.py", line 26, in main
    login()
  File "bot.py", line 21, in login
    identity = handshaker.identify(access_token)
  File "/home/mario/MyProjects/Python/wikibot/venv/lib/python3.7/site-packages/mwoauth/handshaker.py", line 127, in identify
    leeway=leeway, user_agent=self.user_agent)
  File "/home/mario/MyProjects/Python/wikibot/venv/lib/python3.7/site-packages/mwoauth/functions.py", line 268, in identify
    "content: {0}".format(e))
mwoauth.errors.OAuthException: An error occurred while trying to read json content: Invalid header string: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte
```

**Comment by halfak** [comment]
Weird!  Thanks for report.  I'm looking into it.

**Comment by halfak** [comment]
I'm able to run `handshaker.py` in python 3.5.  @moraorviz, are you able to test in an older version of python?

**Comment by moraorviz** [comment]
Hi, I reproduced the error with Python 3.5. The only thing I changed in the script was the wiki url pointing to my own instance.

**Comment by halfak** [comment]
Is your instance returning a valid response?  Can you run `python examples/handshaker.py` directly from the repo?

**Comment by moraorviz** [comment]
I can't because I do not have the accepted account yet to get my credentials for the bot. Anyway your statement about my instance not returning a valid response rings a bell. I am going to investigate that. I think we can close this issue by now.

Thanks for the quick response.

**Comment by halfak** [comment]
OK!  Please re-open if it looks like this is still an issue after your investigations.
