### ISSUE TITLE
handshaker.py is not working for single individual local wiki

### ISSUE THREAD

**Issue by Jayprakash-SE** [mediawiki-utilities/python-mwoauth#31]
This is weird. but handshaker.py giving me an error for individual local wiki. and It is working well when I work on the MediaWiki-Vagrant.
   
**Steps of reproduce**

1. Clone latest mediawiki and install with Extension:OAuth
2. Verify the email through hack (by changing sql table value). So that you can propose for key and secret.
3. Get key and secret and run `python3 handshaker.py`. Paste response query string from oauth_verifier.
4. You will get error for localhost wikis. But did not get for MediaWiki-Vagrant wikis :(

**MediaWiki-Vagrant Response**
```
Jay-Prakash:examples administrator$ python3 handshaker.py
Sending requests with default User-Agent.  Set 'user_agent' on mwoauth.flask.MWOAuth to quiet this message.
Point your browser to: http://dev.wiki.local.wmftest.net:8080/w/index.php?title=Special%3AOAuth%2Fauthenticate&oauth_token=4875d8727d47ad339f29ac7811cacfb3&oauth_consumer_key=8f3490711f1e75c9ad2cb6d99adb4848
Response query string: oauth_verifier=9403ffc8c28263865da1c856e21900dd&oauth_token=4875d8727d47ad339f29ac7811cacfb3
AccessToken(key=b'8e90a03d2b571ad868f41237f1eefc6b', secret=b'f64a6097250d4e88956145f9920710134386f600')
Identified as Admin (id=1).
```

**Localhost Wiki Response**
```
Jay-Prakash:examples administrator$ python3 handshaker.py
Sending requests with default User-Agent.  Set 'user_agent' on mwoauth.flask.MWOAuth to quiet this message.
Point your browser to: http://localhost/MWT/index.php?title=Special%3AOAuth%2Fauthenticate&oauth_token=03f9c70817e0668b2b39e43084da3da0&oauth_consumer_key=dc4229089fa7fb18bb443989e4e1799c
Response query string: oauth_verifier=c7f60f9b025cd33b52e92c900c060762&oauth_token=03f9c70817e0668b2b39e43084da3da0
AccessToken(key=b'401abde555abe5abce1f3da524f14745', secret=b'fc30d163596672ed4cfc78a0217ba393e5172019')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jwt/api_jws.py", line 192, in _load
    header = json.loads(header_data.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mwoauth/functions.py", line 264, in identify
    leeway=leeway)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jwt/api_jwt.py", line 85, in decode
    payload, _, _, _ = self._load(jwt)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jwt/api_jws.py", line 194, in _load
    raise DecodeError('Invalid header string: %s' % e)
jwt.exceptions.DecodeError: Invalid header string: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handshaker.py", line 26, in <module>
    identity = handshaker.identify(access_token)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mwoauth/handshaker.py", line 127, in identify
    leeway=leeway, user_agent=self.user_agent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mwoauth/functions.py", line 268, in identify
    "content: {0}".format(e))
mwoauth.errors.OAuthException: An error occurred while trying to read json content: Invalid header string: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte
```

**Comment by halfak** [comment]
I think this is due to a configuration issue in your local wiki. 

What do you get when you go to localhost/wiki/Special:OAuth/identify?

**Comment by halfak** [comment]
Try out mwoauth version 0.3.5 and you'll get a better error message.
